name: Deployment

on:
    workflow_dispatch:
    push:
        branches: ['main']

jobs:
    unit_testing:
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.ID_RSA }}
                name: id_rsa
                known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - name: Get files
              uses: actions/checkout@v2
            - name: Look at the files
              run: |
                echo $ pwd
                pwd
                echo $ ls -la
                ls -la
